Window.SetBackgroundTopColor(0.035, 0.055, 0.090);
Window.SetBackgroundBottomColor(0.035, 0.055, 0.090);

title_image = Image.Text("NEXOS", "Sans Bold 64", 1, 1, 1);
title = Sprite(title_image);
title.SetX(Window.GetWidth() / 2 - title_image.GetWidth() / 2);
title.SetY(Window.GetHeight() / 2 - 75);

subtitle_image = Image.Text("MADE BY KRITIK BHATTARAI", "Sans 26", 0.85, 0.88, 0.93);
subtitle = Sprite(subtitle_image);
subtitle.SetX(Window.GetWidth() / 2 - subtitle_image.GetWidth() / 2);
subtitle.SetY(Window.GetHeight() / 2 + 15);
