[workspace]
resolver = "3"
members = ["kernel"]

[package]
name = "nexos"
version = "0.1.0"
edition = "2024"
authors = ["Kritik Bhattarai"]
license = "Apache-2.0"
description = "NexOS operating system build and image tooling."

[dependencies]

[build-dependencies]
bootloader = "0.11.17"

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"
lto = true
codegen-units = 1
