# NexOS animated Plymouth loading screen
Window.SetBackgroundTopColor(0.020, 0.039, 0.071);
Window.SetBackgroundBottomColor(0.020, 0.039, 0.071);

logo = Image("/usr/share/backgrounds/nexos.svg");
logo_sprite = Sprite(logo);
logo_sprite.SetX(Window.GetX() + (Window.GetWidth() - logo.GetWidth()) / 2);
logo_sprite.SetY(Window.GetY() + (Window.GetHeight() - logo.GetHeight()) / 2);

spinner_images = [];
for (i = 0; i < 10; i++)
  spinner_images[i] = Image("/usr/share/plymouth/themes/nexos/spinner-" + i + ".svg");

spinner = Sprite();
spinner.SetX(Window.GetX() + Window.GetWidth() / 2 - 32);
spinner.SetY(Window.GetY() + Window.GetHeight() / 2 + 300);

frame = 0;
fun refresh() {
  spinner.SetImage(spinner_images[frame]);
  frame = (frame + 1) % 10;
}
Plymouth.SetRefreshFunction(refresh, 0.10);
